tags:
  - nginx-deploy
substitutions:
  _PROJECT_ID: ${PROJECT_ID}

steps:
- name: ubuntu
  args:
    - echo
    - '${_IMAGE_TAG} ${_ACTION}'

- name: us-central1-docker.pkg.dev/flius-vpc-2/sync-image-repo/builder 
  id: "cloud-deploy"
  entrypoint: bash
  args:
    - '-c'
    - |
      git clone https://github.com/Leisureroad/push-deploy-demo.git && cd push-deploy-demo
      gcloud container clusters get-credentials l4-demo --region us-central1 --project flius-vpc-2
      sed -i 's/IMAGE_TAG/'"${_IMAGE_TAG}"'/g' deployment.yaml
      gcloud beta deploy releases create nginx-${BUILD_ID} \
      --delivery-pipeline=nginx \
      --region=us-central1 \
      --images=nginx-image=${_IMAGE_TAG} \
      --from-k8s-manifest deployment.yaml
