steps:
  # Clone repo
  - name: gcr.io/cloud-builders/git
    args:
      - clone
      - '${_REPO}'
  # Print the content of README.md
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - cd push-deploy-demo && cat README.md
    entrypoint: /bin/sh
substitutions:
  _REPO: https://mygit-647512629680-git.us-central1.sourcemanager.dev/flius-vpc-2/push-deploy-demo.git
